<?php

namespace frontend\components;

use yii\base\InvalidConfigException;
use yii\base\Widget;
use yii\helpers\Html;


class ProgressWidget extends Widget
{
    public $status;
    public $message;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!isset($this->status)){
            throw new InvalidConfigException("Укажите данные аттрибута статус");

        }
    }

    public function run()
    {
        return $this->render('ProgressView', [
            'status' => $this->status,
        ]);
    }
}
