<?php

namespace frontend\components;

use yii\base\Widget;
use common\models\Payments;


class ReportWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $dayStart = mktime(0, 0, 0);
        $dayEnd = $dayStart + 86400;

        $total_cash = Payments::find()->where(['>', 'created', 1601510400])->andWhere(['method_id' => 0])->sum('amount');
        $total_card = Payments::find()->where(['>', 'created', 1601510400])->andWhere(['method_id' => 1])->sum('amount');

        $total_today = Payments::find()->where(['between', 'created', $dayStart, $dayEnd])->andWhere(['method_id' => 0])->sum('amount');
        $today_card = Payments::find()->where(['between', 'created', $dayStart, $dayEnd])->andWhere(['method_id' => 1])->sum('amount');

        return $this->render('ReportView', [

            'total_cash' => $total_cash,
            'total_card' => $total_card,
            'today_cash' => $total_today,
            'today_card' => $today_card,
        ]);
    }
}